qsd_cookbook_parte9/config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes
  resources :recipe_types
  resources :cuisine
end

qsd_cookbook_parte9/app/models/cuisine.rb
class Cuisine < ApplicationRecord
    has_many :recipes

    validates :name, presence: true
end

qsd_cookbook_parte9/app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :recipe_type
  belongs_to :cuisine

  validates :title, :difficulty, :cook_time,
            :ingredients, :cook_method, presence: true

  def cook_time_min
    "#{cook_time} minutos"
  end
end

qsd_cookbook_parte9/app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes

  validates :name, presence: true
end

qsd_cookbook_parte9/app/controllers/cuisine_controller.rb
class CuisineController < ApplicationController
    def show
        cuisine = Cuisine.find(params[:id])
      end
    
      def new
        cuisine = Cuisine.new
      end
    
      def create
        cuisine = Cuisine.new(params.require(:recipe_type).permit(:name))
    
        if cuisine.save
          redirect_to cuisine
        else
          flash[:alert] = 'Você deve informar o nome do tipo de receita'
          render :new
        end
      end
end

qsd_cookbook_parte9/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe_types = RecipeType.all
    @cuisine = Cuisine.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      flash[:alert] = 'Você deve informar todos os dados da receita'
      @recipe_types = RecipeType.all
      @cuisine = Cuisine.all
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe_types = RecipeType.all
    @cuisine = Cuisine.all
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      flash[:alert] = 'Você deve informar todos os dados da receita'
      @recipe_types = RecipeType.all
      @cuisine = Cuisine.all
      render :new
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id, :difficulty,
                                   :cook_time, :ingredients, :cook_method)
  end
end

qsd_cookbook_parte9/app/helpers/cuisine_helper.rb
module CuisineHelper
end

qsd_cookbook_parte9/app/views/recipes/edit.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>
  <%= f.label :recipe_type_id, 'Tipo da Receita' %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>
  <%= f.label :cuisine_id, 'Cozinha' %>
  <%= f.collection_select :cuisine_id, @cuisine, :id, :name %>
  <%= f.label :difficulty, 'Dificuldade' %>
  <%= f.text_field :difficulty %>
  <%= f.label :cook_time, 'Tempo de Preparo' %>
  <%= f.number_field :cook_time %>
  <%= f.label :ingredients, 'Ingredientes' %>
  <%= f.text_area :ingredients %>
  <%= f.label :cook_method, 'Como Preparar' %>
  <%= f.text_area :cook_method %>
  <%= f.submit 'Enviar' %>
<% end %>

qsd_cookbook_parte9/app/views/recipes/index.html.erb
<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<%= link_to 'Enviar uma receita', new_recipe_path %>
<%= link_to 'Cadastrar tipo de receita', new_recipe_type_path %>
<%= link_to 'Cadastrar nova cozinha', new_cuisine_path %>

<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time_min %></li>
  </ul>
<% end %>

qsd_cookbook_parte9/app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>
  <%= f.label :recipe_type_id, 'Tipo da Receita' %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>
  <%= f.label :cuisine_id, 'Cozinha' %>
  <%= f.collection_select :cuisine_id, @cuisine, :id, :name %>
  <%= f.label :difficulty, 'Dificuldade' %>
  <%= f.text_field :difficulty %>
  <%= f.label :cook_time, 'Tempo de Preparo' %>
  <%= f.number_field :cook_time %>
  <%= f.label :ingredients, 'Ingredientes' %>
  <%= f.text_area :ingredients %>
  <%= f.label :cook_method, 'Como Preparar' %>
  <%= f.text_area :cook_method %>
  <%= f.submit 'Enviar' %>
<% end %>